### ISSUE TITLE
Is there a plan to add export `Dict{String,Dict{String,String}}` to bib file?

### ISSUE THREAD

**Issue by htyeim** [stevengj/BibTeX.jl#11]
After getting `result` from `parse_bibtex`, sometimes, I would like to select a part of items in `result` (based on keys) and then export to another bib file. I want if it is possible to add a function (for example `export_bibtex`) to do that? Thank you.

**Comment by Azzaare** [comment]
I don't know for BibTeX.jl (I let someone else answer it), but since BibTeX.jl is now registered, it will be integrated soon into [Bibliography.jl.](https://github.com/Azzaare/Bibliography.jl)
Bibliography.jl will have this function included soon. I can probably do it within today.

EDIT: Done, selection of a part of a bibliography (by intersection or difference of keys) is available. I haven't integrated BibTeX.jl as a registered package yet(it is actually a copy-paste integration ...), but it will not change how to use Bibliography.jl anyway.

**Comment by htyeim** [comment]
I will try that package. I think it is good that reading (parse) and writing (export) functions would be provide in one package 😄. I'm glad that I can always find some packages that do what I want to do in Julia 🤣.  Thank you!
